/* tslint:disable */
/* eslint-disable */
/**
 * Karasu Lab API
 * API documentation for Karasu Lab
 *
 * The version of the OpenAPI document: 4.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CharactersControllerGetRequestWeaponVersionArtifactSetsInner } from './CharactersControllerGetRequestWeaponVersionArtifactSetsInner';
import {
    CharactersControllerGetRequestWeaponVersionArtifactSetsInnerFromJSON,
    CharactersControllerGetRequestWeaponVersionArtifactSetsInnerFromJSONTyped,
    CharactersControllerGetRequestWeaponVersionArtifactSetsInnerToJSON,
    CharactersControllerGetRequestWeaponVersionArtifactSetsInnerToJSONTyped,
} from './CharactersControllerGetRequestWeaponVersionArtifactSetsInner';
import type { CharactersControllerGetRequestWeaponVersionRegionsInner } from './CharactersControllerGetRequestWeaponVersionRegionsInner';
import {
    CharactersControllerGetRequestWeaponVersionRegionsInnerFromJSON,
    CharactersControllerGetRequestWeaponVersionRegionsInnerFromJSONTyped,
    CharactersControllerGetRequestWeaponVersionRegionsInnerToJSON,
    CharactersControllerGetRequestWeaponVersionRegionsInnerToJSONTyped,
} from './CharactersControllerGetRequestWeaponVersionRegionsInner';

/**
 * 
 * @export
 * @interface ArtifactsControllerGetRequestVersion
 */
export interface ArtifactsControllerGetRequestVersion {
    /**
     * 
     * @type {string}
     * @memberof ArtifactsControllerGetRequestVersion
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ArtifactsControllerGetRequestVersion
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ArtifactsControllerGetRequestVersion
     */
    version_string: string;
    /**
     * 
     * @type {boolean}
     * @memberof ArtifactsControllerGetRequestVersion
     */
    released: boolean;
    /**
     * 
     * @type {Array<CharactersControllerGetRequestWeaponVersionArtifactSetsInner>}
     * @memberof ArtifactsControllerGetRequestVersion
     */
    artifact_sets?: Array<CharactersControllerGetRequestWeaponVersionArtifactSetsInner> | null;
    /**
     * 
     * @type {Array<CharactersControllerGetRequestWeaponVersionRegionsInner>}
     * @memberof ArtifactsControllerGetRequestVersion
     */
    regions?: Array<CharactersControllerGetRequestWeaponVersionRegionsInner> | null;
}

/**
 * Check if a given object implements the ArtifactsControllerGetRequestVersion interface.
 */
export function instanceOfArtifactsControllerGetRequestVersion(value: object): value is ArtifactsControllerGetRequestVersion {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('version_string' in value) || value['version_string'] === undefined) return false;
    if (!('released' in value) || value['released'] === undefined) return false;
    return true;
}

export function ArtifactsControllerGetRequestVersionFromJSON(json: any): ArtifactsControllerGetRequestVersion {
    return ArtifactsControllerGetRequestVersionFromJSONTyped(json, false);
}

export function ArtifactsControllerGetRequestVersionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArtifactsControllerGetRequestVersion {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'version_string': json['version_string'],
        'released': json['released'],
        'artifact_sets': json['artifact_sets'] == null ? undefined : ((json['artifact_sets'] as Array<any>).map(CharactersControllerGetRequestWeaponVersionArtifactSetsInnerFromJSON)),
        'regions': json['regions'] == null ? undefined : ((json['regions'] as Array<any>).map(CharactersControllerGetRequestWeaponVersionRegionsInnerFromJSON)),
    };
}

export function ArtifactsControllerGetRequestVersionToJSON(json: any): ArtifactsControllerGetRequestVersion {
    return ArtifactsControllerGetRequestVersionToJSONTyped(json, false);
}

export function ArtifactsControllerGetRequestVersionToJSONTyped(value?: ArtifactsControllerGetRequestVersion | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'version_string': value['version_string'],
        'released': value['released'],
        'artifact_sets': value['artifact_sets'] == null ? undefined : ((value['artifact_sets'] as Array<any>).map(CharactersControllerGetRequestWeaponVersionArtifactSetsInnerToJSON)),
        'regions': value['regions'] == null ? undefined : ((value['regions'] as Array<any>).map(CharactersControllerGetRequestWeaponVersionRegionsInnerToJSON)),
    };
}

