/* tslint:disable */
/* eslint-disable */
/**
 * Karasu Lab API
 * API documentation for Karasu Lab
 *
 * The version of the OpenAPI document: 3.3.20
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ArtifactsControllerGetRequest
 */
export interface ArtifactsControllerGetRequest {
    /**
     * 
     * @type {string}
     * @memberof ArtifactsControllerGetRequest
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ArtifactsControllerGetRequest
     */
    take?: string;
    /**
     * 
     * @type {string}
     * @memberof ArtifactsControllerGetRequest
     */
    skip?: string;
    /**
     * 
     * @type {string}
     * @memberof ArtifactsControllerGetRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ArtifactsControllerGetRequest
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof ArtifactsControllerGetRequest
     */
    icon_url?: string;
    /**
     * 
     * @type {string}
     * @memberof ArtifactsControllerGetRequest
     */
    one_set_effect?: string;
    /**
     * 
     * @type {string}
     * @memberof ArtifactsControllerGetRequest
     */
    two_set_effect?: string;
    /**
     * 
     * @type {string}
     * @memberof ArtifactsControllerGetRequest
     */
    four_set_effect?: string;
    /**
     * 
     * @type {string}
     * @memberof ArtifactsControllerGetRequest
     */
    version?: string;
}

/**
 * Check if a given object implements the ArtifactsControllerGetRequest interface.
 */
export function instanceOfArtifactsControllerGetRequest(value: object): value is ArtifactsControllerGetRequest {
    return true;
}

export function ArtifactsControllerGetRequestFromJSON(json: any): ArtifactsControllerGetRequest {
    return ArtifactsControllerGetRequestFromJSONTyped(json, false);
}

export function ArtifactsControllerGetRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArtifactsControllerGetRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'take': json['take'] == null ? undefined : json['take'],
        'skip': json['skip'] == null ? undefined : json['skip'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'icon_url': json['icon_url'] == null ? undefined : json['icon_url'],
        'one_set_effect': json['one_set_effect'] == null ? undefined : json['one_set_effect'],
        'two_set_effect': json['two_set_effect'] == null ? undefined : json['two_set_effect'],
        'four_set_effect': json['four_set_effect'] == null ? undefined : json['four_set_effect'],
        'version': json['version'] == null ? undefined : json['version'],
    };
}

export function ArtifactsControllerGetRequestToJSON(json: any): ArtifactsControllerGetRequest {
    return ArtifactsControllerGetRequestToJSONTyped(json, false);
}

export function ArtifactsControllerGetRequestToJSONTyped(value?: ArtifactsControllerGetRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'take': value['take'],
        'skip': value['skip'],
        'name': value['name'],
        'description': value['description'],
        'icon_url': value['icon_url'],
        'one_set_effect': value['one_set_effect'],
        'two_set_effect': value['two_set_effect'],
        'four_set_effect': value['four_set_effect'],
        'version': value['version'],
    };
}

