/* tslint:disable */
/* eslint-disable */
/**
 * Karasu Lab API
 * API documentation for Karasu Lab
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ArtifactsControllerGetRequestVersion } from './ArtifactsControllerGetRequestVersion';
import {
    ArtifactsControllerGetRequestVersionFromJSON,
    ArtifactsControllerGetRequestVersionFromJSONTyped,
    ArtifactsControllerGetRequestVersionToJSON,
    ArtifactsControllerGetRequestVersionToJSONTyped,
} from './ArtifactsControllerGetRequestVersion';

/**
 * 
 * @export
 * @interface ArtifactsControllerGetRequest
 */
export interface ArtifactsControllerGetRequest {
    /**
     * 
     * @type {string}
     * @memberof ArtifactsControllerGetRequest
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ArtifactsControllerGetRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ArtifactsControllerGetRequest
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof ArtifactsControllerGetRequest
     */
    icon_url: string;
    /**
     * 
     * @type {ArtifactsControllerGetRequestVersion}
     * @memberof ArtifactsControllerGetRequest
     */
    version: ArtifactsControllerGetRequestVersion;
}

/**
 * Check if a given object implements the ArtifactsControllerGetRequest interface.
 */
export function instanceOfArtifactsControllerGetRequest(value: object): value is ArtifactsControllerGetRequest {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('icon_url' in value) || value['icon_url'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    return true;
}

export function ArtifactsControllerGetRequestFromJSON(json: any): ArtifactsControllerGetRequest {
    return ArtifactsControllerGetRequestFromJSONTyped(json, false);
}

export function ArtifactsControllerGetRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArtifactsControllerGetRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'],
        'icon_url': json['icon_url'],
        'version': ArtifactsControllerGetRequestVersionFromJSON(json['version']),
    };
}

export function ArtifactsControllerGetRequestToJSON(json: any): ArtifactsControllerGetRequest {
    return ArtifactsControllerGetRequestToJSONTyped(json, false);
}

export function ArtifactsControllerGetRequestToJSONTyped(value?: ArtifactsControllerGetRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'icon_url': value['icon_url'],
        'version': ArtifactsControllerGetRequestVersionToJSON(value['version']),
    };
}

