/* tslint:disable */
/* eslint-disable */
/**
 * Karasu Lab API
 * API documentation for Karasu Lab
 *
 * The version of the OpenAPI document: 4.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CharactersControllerGetRequestGalleriesInner
 */
export interface CharactersControllerGetRequestGalleriesInner {
    /**
     * 
     * @type {string}
     * @memberof CharactersControllerGetRequestGalleriesInner
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CharactersControllerGetRequestGalleriesInner
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof CharactersControllerGetRequestGalleriesInner
     */
    alt: string;
    /**
     * 
     * @type {string}
     * @memberof CharactersControllerGetRequestGalleriesInner
     */
    key?: string;
    /**
     * 
     * @type {string}
     * @memberof CharactersControllerGetRequestGalleriesInner
     */
    character?: string;
    /**
     * 
     * @type {string}
     * @memberof CharactersControllerGetRequestGalleriesInner
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof CharactersControllerGetRequestGalleriesInner
     */
    updatedAt: string;
}

/**
 * Check if a given object implements the CharactersControllerGetRequestGalleriesInner interface.
 */
export function instanceOfCharactersControllerGetRequestGalleriesInner(value: object): value is CharactersControllerGetRequestGalleriesInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('alt' in value) || value['alt'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function CharactersControllerGetRequestGalleriesInnerFromJSON(json: any): CharactersControllerGetRequestGalleriesInner {
    return CharactersControllerGetRequestGalleriesInnerFromJSONTyped(json, false);
}

export function CharactersControllerGetRequestGalleriesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CharactersControllerGetRequestGalleriesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'url': json['url'],
        'alt': json['alt'],
        'key': json['key'] == null ? undefined : json['key'],
        'character': json['character'] == null ? undefined : json['character'],
        'createdAt': json['createdAt'],
        'updatedAt': json['updatedAt'],
    };
}

export function CharactersControllerGetRequestGalleriesInnerToJSON(json: any): CharactersControllerGetRequestGalleriesInner {
    return CharactersControllerGetRequestGalleriesInnerToJSONTyped(json, false);
}

export function CharactersControllerGetRequestGalleriesInnerToJSONTyped(value?: CharactersControllerGetRequestGalleriesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'url': value['url'],
        'alt': value['alt'],
        'key': value['key'],
        'character': value['character'],
        'createdAt': value['createdAt'],
        'updatedAt': value['updatedAt'],
    };
}

