/* tslint:disable */
/* eslint-disable */
/**
 * Karasu Lab API
 * API documentation for Karasu Lab
 *
 * The version of the OpenAPI document: 4.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CharactersControllerGetRequestWeaponVersion } from './CharactersControllerGetRequestWeaponVersion';
import {
    CharactersControllerGetRequestWeaponVersionFromJSON,
    CharactersControllerGetRequestWeaponVersionFromJSONTyped,
    CharactersControllerGetRequestWeaponVersionToJSON,
    CharactersControllerGetRequestWeaponVersionToJSONTyped,
} from './CharactersControllerGetRequestWeaponVersion';

/**
 * 
 * @export
 * @interface CharactersControllerGetRequestWeapon
 */
export interface CharactersControllerGetRequestWeapon {
    /**
     * 
     * @type {string}
     * @memberof CharactersControllerGetRequestWeapon
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CharactersControllerGetRequestWeapon
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CharactersControllerGetRequestWeapon
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CharactersControllerGetRequestWeapon
     */
    icon_url: string;
    /**
     * 
     * @type {number}
     * @memberof CharactersControllerGetRequestWeapon
     */
    rarity: number;
    /**
     * 
     * @type {string}
     * @memberof CharactersControllerGetRequestWeapon
     */
    effect: string;
    /**
     * 
     * @type {string}
     * @memberof CharactersControllerGetRequestWeapon
     */
    type: string;
    /**
     * 
     * @type {CharactersControllerGetRequestWeaponVersion}
     * @memberof CharactersControllerGetRequestWeapon
     */
    version: CharactersControllerGetRequestWeaponVersion;
    /**
     * 
     * @type {string}
     * @memberof CharactersControllerGetRequestWeapon
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof CharactersControllerGetRequestWeapon
     */
    updatedAt: string;
}

/**
 * Check if a given object implements the CharactersControllerGetRequestWeapon interface.
 */
export function instanceOfCharactersControllerGetRequestWeapon(value: object): value is CharactersControllerGetRequestWeapon {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('icon_url' in value) || value['icon_url'] === undefined) return false;
    if (!('rarity' in value) || value['rarity'] === undefined) return false;
    if (!('effect' in value) || value['effect'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function CharactersControllerGetRequestWeaponFromJSON(json: any): CharactersControllerGetRequestWeapon {
    return CharactersControllerGetRequestWeaponFromJSONTyped(json, false);
}

export function CharactersControllerGetRequestWeaponFromJSONTyped(json: any, ignoreDiscriminator: boolean): CharactersControllerGetRequestWeapon {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'icon_url': json['icon_url'],
        'rarity': json['rarity'],
        'effect': json['effect'],
        'type': json['type'],
        'version': CharactersControllerGetRequestWeaponVersionFromJSON(json['version']),
        'createdAt': json['createdAt'],
        'updatedAt': json['updatedAt'],
    };
}

export function CharactersControllerGetRequestWeaponToJSON(json: any): CharactersControllerGetRequestWeapon {
    return CharactersControllerGetRequestWeaponToJSONTyped(json, false);
}

export function CharactersControllerGetRequestWeaponToJSONTyped(value?: CharactersControllerGetRequestWeapon | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'icon_url': value['icon_url'],
        'rarity': value['rarity'],
        'effect': value['effect'],
        'type': value['type'],
        'version': CharactersControllerGetRequestWeaponVersionToJSON(value['version']),
        'createdAt': value['createdAt'],
        'updatedAt': value['updatedAt'],
    };
}

