/* tslint:disable */
/* eslint-disable */
/**
 * Karasu Lab API
 * API documentation for Karasu Lab
 *
 * The version of the OpenAPI document: 4.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CharactersControllerGetRequestArtifactSetInner
 */
export interface CharactersControllerGetRequestArtifactSetInner {
    /**
     * 
     * @type {string}
     * @memberof CharactersControllerGetRequestArtifactSetInner
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CharactersControllerGetRequestArtifactSetInner
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CharactersControllerGetRequestArtifactSetInner
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof CharactersControllerGetRequestArtifactSetInner
     */
    icon_url: string;
    /**
     * 
     * @type {number}
     * @memberof CharactersControllerGetRequestArtifactSetInner
     */
    rarity: number;
    /**
     * 
     * @type {string}
     * @memberof CharactersControllerGetRequestArtifactSetInner
     */
    one_set_effect: string;
    /**
     * 
     * @type {string}
     * @memberof CharactersControllerGetRequestArtifactSetInner
     */
    two_set_effect: string;
    /**
     * 
     * @type {string}
     * @memberof CharactersControllerGetRequestArtifactSetInner
     */
    four_set_effect: string;
    /**
     * 
     * @type {string}
     * @memberof CharactersControllerGetRequestArtifactSetInner
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof CharactersControllerGetRequestArtifactSetInner
     */
    updatedAt: string;
}

/**
 * Check if a given object implements the CharactersControllerGetRequestArtifactSetInner interface.
 */
export function instanceOfCharactersControllerGetRequestArtifactSetInner(value: object): value is CharactersControllerGetRequestArtifactSetInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('icon_url' in value) || value['icon_url'] === undefined) return false;
    if (!('rarity' in value) || value['rarity'] === undefined) return false;
    if (!('one_set_effect' in value) || value['one_set_effect'] === undefined) return false;
    if (!('two_set_effect' in value) || value['two_set_effect'] === undefined) return false;
    if (!('four_set_effect' in value) || value['four_set_effect'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function CharactersControllerGetRequestArtifactSetInnerFromJSON(json: any): CharactersControllerGetRequestArtifactSetInner {
    return CharactersControllerGetRequestArtifactSetInnerFromJSONTyped(json, false);
}

export function CharactersControllerGetRequestArtifactSetInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CharactersControllerGetRequestArtifactSetInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'],
        'icon_url': json['icon_url'],
        'rarity': json['rarity'],
        'one_set_effect': json['one_set_effect'],
        'two_set_effect': json['two_set_effect'],
        'four_set_effect': json['four_set_effect'],
        'createdAt': json['createdAt'],
        'updatedAt': json['updatedAt'],
    };
}

export function CharactersControllerGetRequestArtifactSetInnerToJSON(json: any): CharactersControllerGetRequestArtifactSetInner {
    return CharactersControllerGetRequestArtifactSetInnerToJSONTyped(json, false);
}

export function CharactersControllerGetRequestArtifactSetInnerToJSONTyped(value?: CharactersControllerGetRequestArtifactSetInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'icon_url': value['icon_url'],
        'rarity': value['rarity'],
        'one_set_effect': value['one_set_effect'],
        'two_set_effect': value['two_set_effect'],
        'four_set_effect': value['four_set_effect'],
        'createdAt': value['createdAt'],
        'updatedAt': value['updatedAt'],
    };
}

