/* tslint:disable */
/* eslint-disable */
/**
 * Karasu Lab API
 * API documentation for Karasu Lab
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CharactersControllerGetRequestWeaponVersionRegionsInner
 */
export interface CharactersControllerGetRequestWeaponVersionRegionsInner {
    /**
     * 
     * @type {string}
     * @memberof CharactersControllerGetRequestWeaponVersionRegionsInner
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CharactersControllerGetRequestWeaponVersionRegionsInner
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CharactersControllerGetRequestWeaponVersionRegionsInner
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CharactersControllerGetRequestWeaponVersionRegionsInner
     */
    icon_url: string;
    /**
     * 
     * @type {string}
     * @memberof CharactersControllerGetRequestWeaponVersionRegionsInner
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof CharactersControllerGetRequestWeaponVersionRegionsInner
     */
    updatedAt: string;
}

/**
 * Check if a given object implements the CharactersControllerGetRequestWeaponVersionRegionsInner interface.
 */
export function instanceOfCharactersControllerGetRequestWeaponVersionRegionsInner(value: object): value is CharactersControllerGetRequestWeaponVersionRegionsInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('icon_url' in value) || value['icon_url'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function CharactersControllerGetRequestWeaponVersionRegionsInnerFromJSON(json: any): CharactersControllerGetRequestWeaponVersionRegionsInner {
    return CharactersControllerGetRequestWeaponVersionRegionsInnerFromJSONTyped(json, false);
}

export function CharactersControllerGetRequestWeaponVersionRegionsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CharactersControllerGetRequestWeaponVersionRegionsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'icon_url': json['icon_url'],
        'createdAt': json['createdAt'],
        'updatedAt': json['updatedAt'],
    };
}

export function CharactersControllerGetRequestWeaponVersionRegionsInnerToJSON(json: any): CharactersControllerGetRequestWeaponVersionRegionsInner {
    return CharactersControllerGetRequestWeaponVersionRegionsInnerToJSONTyped(json, false);
}

export function CharactersControllerGetRequestWeaponVersionRegionsInnerToJSONTyped(value?: CharactersControllerGetRequestWeaponVersionRegionsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'icon_url': value['icon_url'],
        'createdAt': value['createdAt'],
        'updatedAt': value['updatedAt'],
    };
}

