/* tslint:disable */
/* eslint-disable */
/**
 * Karasu Lab API
 * API documentation for Karasu Lab
 *
 * The version of the OpenAPI document: 4.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CharactersControllerGetRequestRegion } from './CharactersControllerGetRequestRegion';
import {
    CharactersControllerGetRequestRegionFromJSON,
    CharactersControllerGetRequestRegionFromJSONTyped,
    CharactersControllerGetRequestRegionToJSON,
    CharactersControllerGetRequestRegionToJSONTyped,
} from './CharactersControllerGetRequestRegion';
import type { CharactersControllerGetRequestWeapon } from './CharactersControllerGetRequestWeapon';
import {
    CharactersControllerGetRequestWeaponFromJSON,
    CharactersControllerGetRequestWeaponFromJSONTyped,
    CharactersControllerGetRequestWeaponToJSON,
    CharactersControllerGetRequestWeaponToJSONTyped,
} from './CharactersControllerGetRequestWeapon';
import type { CharactersControllerGetRequestArtifactSetInner } from './CharactersControllerGetRequestArtifactSetInner';
import {
    CharactersControllerGetRequestArtifactSetInnerFromJSON,
    CharactersControllerGetRequestArtifactSetInnerFromJSONTyped,
    CharactersControllerGetRequestArtifactSetInnerToJSON,
    CharactersControllerGetRequestArtifactSetInnerToJSONTyped,
} from './CharactersControllerGetRequestArtifactSetInner';
import type { CharactersControllerGetRequestVersion } from './CharactersControllerGetRequestVersion';
import {
    CharactersControllerGetRequestVersionFromJSON,
    CharactersControllerGetRequestVersionFromJSONTyped,
    CharactersControllerGetRequestVersionToJSON,
    CharactersControllerGetRequestVersionToJSONTyped,
} from './CharactersControllerGetRequestVersion';
import type { CharactersControllerGetRequestGalleriesInner } from './CharactersControllerGetRequestGalleriesInner';
import {
    CharactersControllerGetRequestGalleriesInnerFromJSON,
    CharactersControllerGetRequestGalleriesInnerFromJSONTyped,
    CharactersControllerGetRequestGalleriesInnerToJSON,
    CharactersControllerGetRequestGalleriesInnerToJSONTyped,
} from './CharactersControllerGetRequestGalleriesInner';

/**
 * 
 * @export
 * @interface CountriesControllerGetRequestCharactersInner
 */
export interface CountriesControllerGetRequestCharactersInner {
    /**
     * 
     * @type {string}
     * @memberof CountriesControllerGetRequestCharactersInner
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CountriesControllerGetRequestCharactersInner
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CountriesControllerGetRequestCharactersInner
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CountriesControllerGetRequestCharactersInner
     */
    icon_url: string;
    /**
     * 
     * @type {string}
     * @memberof CountriesControllerGetRequestCharactersInner
     */
    element?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CountriesControllerGetRequestCharactersInner
     */
    rarity?: number | null;
    /**
     * 
     * @type {string}
     * @memberof CountriesControllerGetRequestCharactersInner
     */
    header_img_url?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CountriesControllerGetRequestCharactersInner
     */
    weapon_type?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CountriesControllerGetRequestCharactersInner
     */
    property?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof CountriesControllerGetRequestCharactersInner
     */
    unimplemented?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CountriesControllerGetRequestCharactersInner
     */
    implemented_date?: string | null;
    /**
     * 
     * @type {CharactersControllerGetRequestRegion}
     * @memberof CountriesControllerGetRequestCharactersInner
     */
    region?: CharactersControllerGetRequestRegion | null;
    /**
     * 
     * @type {CharactersControllerGetRequestWeapon}
     * @memberof CountriesControllerGetRequestCharactersInner
     */
    weapon?: CharactersControllerGetRequestWeapon | null;
    /**
     * 
     * @type {CharactersControllerGetRequestVersion}
     * @memberof CountriesControllerGetRequestCharactersInner
     */
    version?: CharactersControllerGetRequestVersion | null;
    /**
     * 
     * @type {Array<CharactersControllerGetRequestGalleriesInner>}
     * @memberof CountriesControllerGetRequestCharactersInner
     */
    galleries?: Array<CharactersControllerGetRequestGalleriesInner> | null;
    /**
     * 
     * @type {Array<CharactersControllerGetRequestArtifactSetInner>}
     * @memberof CountriesControllerGetRequestCharactersInner
     */
    artifact_set?: Array<CharactersControllerGetRequestArtifactSetInner> | null;
}

/**
 * Check if a given object implements the CountriesControllerGetRequestCharactersInner interface.
 */
export function instanceOfCountriesControllerGetRequestCharactersInner(value: object): value is CountriesControllerGetRequestCharactersInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('icon_url' in value) || value['icon_url'] === undefined) return false;
    return true;
}

export function CountriesControllerGetRequestCharactersInnerFromJSON(json: any): CountriesControllerGetRequestCharactersInner {
    return CountriesControllerGetRequestCharactersInnerFromJSONTyped(json, false);
}

export function CountriesControllerGetRequestCharactersInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CountriesControllerGetRequestCharactersInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'icon_url': json['icon_url'],
        'element': json['element'] == null ? undefined : json['element'],
        'rarity': json['rarity'] == null ? undefined : json['rarity'],
        'header_img_url': json['header_img_url'] == null ? undefined : json['header_img_url'],
        'weapon_type': json['weapon_type'] == null ? undefined : json['weapon_type'],
        'property': json['property'] == null ? undefined : json['property'],
        'unimplemented': json['unimplemented'] == null ? undefined : json['unimplemented'],
        'implemented_date': json['implemented_date'] == null ? undefined : json['implemented_date'],
        'region': json['region'] == null ? undefined : CharactersControllerGetRequestRegionFromJSON(json['region']),
        'weapon': json['weapon'] == null ? undefined : CharactersControllerGetRequestWeaponFromJSON(json['weapon']),
        'version': json['version'] == null ? undefined : CharactersControllerGetRequestVersionFromJSON(json['version']),
        'galleries': json['galleries'] == null ? undefined : ((json['galleries'] as Array<any>).map(CharactersControllerGetRequestGalleriesInnerFromJSON)),
        'artifact_set': json['artifact_set'] == null ? undefined : ((json['artifact_set'] as Array<any>).map(CharactersControllerGetRequestArtifactSetInnerFromJSON)),
    };
}

export function CountriesControllerGetRequestCharactersInnerToJSON(json: any): CountriesControllerGetRequestCharactersInner {
    return CountriesControllerGetRequestCharactersInnerToJSONTyped(json, false);
}

export function CountriesControllerGetRequestCharactersInnerToJSONTyped(value?: CountriesControllerGetRequestCharactersInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'icon_url': value['icon_url'],
        'element': value['element'],
        'rarity': value['rarity'],
        'header_img_url': value['header_img_url'],
        'weapon_type': value['weapon_type'],
        'property': value['property'],
        'unimplemented': value['unimplemented'],
        'implemented_date': value['implemented_date'],
        'region': CharactersControllerGetRequestRegionToJSON(value['region']),
        'weapon': CharactersControllerGetRequestWeaponToJSON(value['weapon']),
        'version': CharactersControllerGetRequestVersionToJSON(value['version']),
        'galleries': value['galleries'] == null ? undefined : ((value['galleries'] as Array<any>).map(CharactersControllerGetRequestGalleriesInnerToJSON)),
        'artifact_set': value['artifact_set'] == null ? undefined : ((value['artifact_set'] as Array<any>).map(CharactersControllerGetRequestArtifactSetInnerToJSON)),
    };
}

