/* tslint:disable */
/* eslint-disable */
/**
 * Karasu Lab Auth API Document Production
 * API documentation for Karasu Lab
 *
 * The version of the OpenAPI document: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GalleriesControllerUpdateRequest
 */
export interface GalleriesControllerUpdateRequest {
    /**
     * 
     * @type {string}
     * @memberof GalleriesControllerUpdateRequest
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof GalleriesControllerUpdateRequest
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof GalleriesControllerUpdateRequest
     */
    alt: string;
    /**
     * 
     * @type {string}
     * @memberof GalleriesControllerUpdateRequest
     */
    key: string;
    /**
     * 
     * @type {string}
     * @memberof GalleriesControllerUpdateRequest
     */
    character: string;
}

/**
 * Check if a given object implements the GalleriesControllerUpdateRequest interface.
 */
export function instanceOfGalleriesControllerUpdateRequest(value: object): value is GalleriesControllerUpdateRequest {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('alt' in value) || value['alt'] === undefined) return false;
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('character' in value) || value['character'] === undefined) return false;
    return true;
}

export function GalleriesControllerUpdateRequestFromJSON(json: any): GalleriesControllerUpdateRequest {
    return GalleriesControllerUpdateRequestFromJSONTyped(json, false);
}

export function GalleriesControllerUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GalleriesControllerUpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'url': json['url'],
        'alt': json['alt'],
        'key': json['key'],
        'character': json['character'],
    };
}

export function GalleriesControllerUpdateRequestToJSON(json: any): GalleriesControllerUpdateRequest {
    return GalleriesControllerUpdateRequestToJSONTyped(json, false);
}

export function GalleriesControllerUpdateRequestToJSONTyped(value?: GalleriesControllerUpdateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'url': value['url'],
        'alt': value['alt'],
        'key': value['key'],
        'character': value['character'],
    };
}

