/* tslint:disable */
/* eslint-disable */
/**
 * Karasu Lab Auth API Document Production
 * API documentation for Karasu Lab
 *
 * The version of the OpenAPI document: 3.3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GalleriesControllerCreateRequest
 */
export interface GalleriesControllerCreateRequest {
    /**
     * 
     * @type {string}
     * @memberof GalleriesControllerCreateRequest
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof GalleriesControllerCreateRequest
     */
    alt: string;
    /**
     * 
     * @type {string}
     * @memberof GalleriesControllerCreateRequest
     */
    key: string;
    /**
     * 
     * @type {string}
     * @memberof GalleriesControllerCreateRequest
     */
    character: string;
}

/**
 * Check if a given object implements the GalleriesControllerCreateRequest interface.
 */
export function instanceOfGalleriesControllerCreateRequest(value: object): value is GalleriesControllerCreateRequest {
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('alt' in value) || value['alt'] === undefined) return false;
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('character' in value) || value['character'] === undefined) return false;
    return true;
}

export function GalleriesControllerCreateRequestFromJSON(json: any): GalleriesControllerCreateRequest {
    return GalleriesControllerCreateRequestFromJSONTyped(json, false);
}

export function GalleriesControllerCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GalleriesControllerCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
        'alt': json['alt'],
        'key': json['key'],
        'character': json['character'],
    };
}

export function GalleriesControllerCreateRequestToJSON(json: any): GalleriesControllerCreateRequest {
    return GalleriesControllerCreateRequestToJSONTyped(json, false);
}

export function GalleriesControllerCreateRequestToJSONTyped(value?: GalleriesControllerCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
        'alt': value['alt'],
        'key': value['key'],
        'character': value['character'],
    };
}

