/* tslint:disable */
/* eslint-disable */
/**
 * Karasu Lab API
 * API documentation for Karasu Lab
 *
 * The version of the OpenAPI document: 3.3.32
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HI3Characters } from './HI3Characters';
import {
    HI3CharactersFromJSON,
    HI3CharactersFromJSONTyped,
    HI3CharactersToJSON,
    HI3CharactersToJSONTyped,
} from './HI3Characters';

/**
 * 
 * @export
 * @interface HI3SkillsEntity
 */
export interface HI3SkillsEntity {
    /**
     * 
     * @type {string}
     * @memberof HI3SkillsEntity
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof HI3SkillsEntity
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof HI3SkillsEntity
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof HI3SkillsEntity
     */
    type?: string | null;
    /**
     * 
     * @type {number}
     * @memberof HI3SkillsEntity
     */
    max_level?: number | null;
    /**
     * 
     * @type {string}
     * @memberof HI3SkillsEntity
     */
    icon_url?: string | null;
    /**
     * 
     * @type {HI3Characters}
     * @memberof HI3SkillsEntity
     */
    characters?: HI3Characters | null;
}

/**
 * Check if a given object implements the HI3SkillsEntity interface.
 */
export function instanceOfHI3SkillsEntity(value: object): value is HI3SkillsEntity {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function HI3SkillsEntityFromJSON(json: any): HI3SkillsEntity {
    return HI3SkillsEntityFromJSONTyped(json, false);
}

export function HI3SkillsEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): HI3SkillsEntity {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'type': json['type'] == null ? undefined : json['type'],
        'max_level': json['max_level'] == null ? undefined : json['max_level'],
        'icon_url': json['icon_url'] == null ? undefined : json['icon_url'],
        'characters': json['characters'] == null ? undefined : HI3CharactersFromJSON(json['characters']),
    };
}

export function HI3SkillsEntityToJSON(json: any): HI3SkillsEntity {
    return HI3SkillsEntityToJSONTyped(json, false);
}

export function HI3SkillsEntityToJSONTyped(value?: HI3SkillsEntity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'type': value['type'],
        'max_level': value['max_level'],
        'icon_url': value['icon_url'],
        'characters': HI3CharactersToJSON(value['characters']),
    };
}

