/* tslint:disable */
/* eslint-disable */
/**
 * Karasu Lab API
 * API documentation for Karasu Lab
 *
 * The version of the OpenAPI document: 4.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CharactersControllerGetRequestWeaponVersionArtifactSetsInner } from './CharactersControllerGetRequestWeaponVersionArtifactSetsInner';
import {
    CharactersControllerGetRequestWeaponVersionArtifactSetsInnerFromJSON,
    CharactersControllerGetRequestWeaponVersionArtifactSetsInnerFromJSONTyped,
    CharactersControllerGetRequestWeaponVersionArtifactSetsInnerToJSON,
    CharactersControllerGetRequestWeaponVersionArtifactSetsInnerToJSONTyped,
} from './CharactersControllerGetRequestWeaponVersionArtifactSetsInner';
import type { CharactersControllerGetRequestWeaponVersionRegionsInner } from './CharactersControllerGetRequestWeaponVersionRegionsInner';
import {
    CharactersControllerGetRequestWeaponVersionRegionsInnerFromJSON,
    CharactersControllerGetRequestWeaponVersionRegionsInnerFromJSONTyped,
    CharactersControllerGetRequestWeaponVersionRegionsInnerToJSON,
    CharactersControllerGetRequestWeaponVersionRegionsInnerToJSONTyped,
} from './CharactersControllerGetRequestWeaponVersionRegionsInner';

/**
 * 
 * @export
 * @interface VersionsControllerGetRequest
 */
export interface VersionsControllerGetRequest {
    /**
     * 
     * @type {string}
     * @memberof VersionsControllerGetRequest
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof VersionsControllerGetRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof VersionsControllerGetRequest
     */
    version_string?: string;
    /**
     * 
     * @type {boolean}
     * @memberof VersionsControllerGetRequest
     */
    released?: boolean;
    /**
     * 
     * @type {Array<CharactersControllerGetRequestWeaponVersionArtifactSetsInner>}
     * @memberof VersionsControllerGetRequest
     */
    artifact_sets?: Array<CharactersControllerGetRequestWeaponVersionArtifactSetsInner> | null;
    /**
     * 
     * @type {Array<CharactersControllerGetRequestWeaponVersionRegionsInner>}
     * @memberof VersionsControllerGetRequest
     */
    regions?: Array<CharactersControllerGetRequestWeaponVersionRegionsInner> | null;
}

/**
 * Check if a given object implements the VersionsControllerGetRequest interface.
 */
export function instanceOfVersionsControllerGetRequest(value: object): value is VersionsControllerGetRequest {
    return true;
}

export function VersionsControllerGetRequestFromJSON(json: any): VersionsControllerGetRequest {
    return VersionsControllerGetRequestFromJSONTyped(json, false);
}

export function VersionsControllerGetRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): VersionsControllerGetRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'version_string': json['version_string'] == null ? undefined : json['version_string'],
        'released': json['released'] == null ? undefined : json['released'],
        'artifact_sets': json['artifact_sets'] == null ? undefined : ((json['artifact_sets'] as Array<any>).map(CharactersControllerGetRequestWeaponVersionArtifactSetsInnerFromJSON)),
        'regions': json['regions'] == null ? undefined : ((json['regions'] as Array<any>).map(CharactersControllerGetRequestWeaponVersionRegionsInnerFromJSON)),
    };
}

export function VersionsControllerGetRequestToJSON(json: any): VersionsControllerGetRequest {
    return VersionsControllerGetRequestToJSONTyped(json, false);
}

export function VersionsControllerGetRequestToJSONTyped(value?: VersionsControllerGetRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'version_string': value['version_string'],
        'released': value['released'],
        'artifact_sets': value['artifact_sets'] == null ? undefined : ((value['artifact_sets'] as Array<any>).map(CharactersControllerGetRequestWeaponVersionArtifactSetsInnerToJSON)),
        'regions': value['regions'] == null ? undefined : ((value['regions'] as Array<any>).map(CharactersControllerGetRequestWeaponVersionRegionsInnerToJSON)),
    };
}

