/**
 * Karasu Lab API production
 * API documentation for Karasu Lab
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Artifacts } from '../models/Artifacts';
import { Character } from '../models/Character';
import { VersionsEntity } from '../models/VersionsEntity';
import { HttpFile } from '../http/http';

export class ArtifactSets {
    'id': string;
    'name': string;
    'description': string;
    'iconUrl': string;
    'oneSetEffect': string;
    'twoSetEffect': string;
    'fourSetEffect': string;
    'createdAt': Date;
    'updatedAt': Date;
    'artifacts': Array<Artifacts>;
    'characters': Array<Character>;
    'version': VersionsEntity;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "iconUrl",
            "baseName": "icon_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "oneSetEffect",
            "baseName": "one_set_effect",
            "type": "string",
            "format": ""
        },
        {
            "name": "twoSetEffect",
            "baseName": "two_set_effect",
            "type": "string",
            "format": ""
        },
        {
            "name": "fourSetEffect",
            "baseName": "four_set_effect",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "artifacts",
            "baseName": "artifacts",
            "type": "Array<Artifacts>",
            "format": ""
        },
        {
            "name": "characters",
            "baseName": "characters",
            "type": "Array<Character>",
            "format": ""
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "VersionsEntity",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ArtifactSets.attributeTypeMap;
    }

    public constructor() {
    }
}
