/**
 * Karasu Lab API production
 * API documentation for Karasu Lab
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CharactersControllerImportRequestFilterValuesCharacterPropertyKey } from '../models/CharactersControllerImportRequestFilterValuesCharacterPropertyKey';
import { CharactersControllerImportRequestFilterValuesCharacterPropertyValueTypesInner } from '../models/CharactersControllerImportRequestFilterValuesCharacterPropertyValueTypesInner';
import { HttpFile } from '../http/http';

export class CharactersControllerImportRequestFilterValuesCharacterProperty {
    'values'?: Array<string>;
    'valueTypes'?: Array<CharactersControllerImportRequestFilterValuesCharacterPropertyValueTypesInner>;
    'key': CharactersControllerImportRequestFilterValuesCharacterPropertyKey | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "values",
            "baseName": "values",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "valueTypes",
            "baseName": "value_types",
            "type": "Array<CharactersControllerImportRequestFilterValuesCharacterPropertyValueTypesInner>",
            "format": ""
        },
        {
            "name": "key",
            "baseName": "key",
            "type": "CharactersControllerImportRequestFilterValuesCharacterPropertyKey",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CharactersControllerImportRequestFilterValuesCharacterProperty.attributeTypeMap;
    }

    public constructor() {
    }
}
