/**
 * Karasu Lab API production
 * API documentation for Karasu Lab
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CharactersControllerImportFromHoyoLabQueryParameter {
    'entryPageId': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "entryPageId",
            "baseName": "entry_page_id",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CharactersControllerImportFromHoyoLabQueryParameter.attributeTypeMap;
    }

    public constructor() {
    }
}
