/**
 * Karasu Lab API production
 * API documentation for Karasu Lab
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CharactersControllerImportRequestFilterValuesCharacterProperty } from '../models/CharactersControllerImportRequestFilterValuesCharacterProperty';
import { HttpFile } from '../http/http';

export class CharactersControllerImportRequestFilterValues {
    'characterProperty'?: CharactersControllerImportRequestFilterValuesCharacterProperty;
    'characterWeapon'?: CharactersControllerImportRequestFilterValuesCharacterProperty;
    'characterRarity'?: CharactersControllerImportRequestFilterValuesCharacterProperty;
    'characterVision'?: CharactersControllerImportRequestFilterValuesCharacterProperty;
    'characterRegion'?: CharactersControllerImportRequestFilterValuesCharacterProperty;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "characterProperty",
            "baseName": "character_property",
            "type": "CharactersControllerImportRequestFilterValuesCharacterProperty",
            "format": ""
        },
        {
            "name": "characterWeapon",
            "baseName": "character_weapon",
            "type": "CharactersControllerImportRequestFilterValuesCharacterProperty",
            "format": ""
        },
        {
            "name": "characterRarity",
            "baseName": "character_rarity",
            "type": "CharactersControllerImportRequestFilterValuesCharacterProperty",
            "format": ""
        },
        {
            "name": "characterVision",
            "baseName": "character_vision",
            "type": "CharactersControllerImportRequestFilterValuesCharacterProperty",
            "format": ""
        },
        {
            "name": "characterRegion",
            "baseName": "character_region",
            "type": "CharactersControllerImportRequestFilterValuesCharacterProperty",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CharactersControllerImportRequestFilterValues.attributeTypeMap;
    }

    public constructor() {
    }
}
