/**
 * Karasu Lab API production
 * API documentation for Karasu Lab
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CharactersControllerImportRequestFilterValuesCharacterPropertyKey {
    'key': string;
    'text': string;
    'values'?: Array<string>;
    'mi18nKey': string;
    'isMultiSelect'?: boolean;
    'id': string;
    'isHidden'?: boolean;
    'updatedAt': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "key",
            "baseName": "key",
            "type": "string",
            "format": ""
        },
        {
            "name": "text",
            "baseName": "text",
            "type": "string",
            "format": ""
        },
        {
            "name": "values",
            "baseName": "values",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "mi18nKey",
            "baseName": "mi18n_key",
            "type": "string",
            "format": ""
        },
        {
            "name": "isMultiSelect",
            "baseName": "is_multi_select",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "isHidden",
            "baseName": "is_hidden",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CharactersControllerImportRequestFilterValuesCharacterPropertyKey.attributeTypeMap;
    }

    public constructor() {
    }
}
