/**
 * Karasu Lab API production
 * API documentation for Karasu Lab
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CharactersControllerImportRequestExtPostExt } from '../models/CharactersControllerImportRequestExtPostExt';
import { HttpFile } from '../http/http';

export class CharactersControllerImportRequestExt {
    'feExt': string;
    'postExt': CharactersControllerImportRequestExtPostExt;
    'serverExt': string;
    'personalizedColor': string;
    'scrollingText': string;
    'cornerMark': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "feExt",
            "baseName": "fe_ext",
            "type": "string",
            "format": ""
        },
        {
            "name": "postExt",
            "baseName": "post_ext",
            "type": "CharactersControllerImportRequestExtPostExt",
            "format": ""
        },
        {
            "name": "serverExt",
            "baseName": "server_ext",
            "type": "string",
            "format": ""
        },
        {
            "name": "personalizedColor",
            "baseName": "personalized_color",
            "type": "string",
            "format": ""
        },
        {
            "name": "scrollingText",
            "baseName": "scrolling_text",
            "type": "string",
            "format": ""
        },
        {
            "name": "cornerMark",
            "baseName": "corner_mark",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CharactersControllerImportRequestExt.attributeTypeMap;
    }

    public constructor() {
    }
}
