/**
 * Karasu Lab API production
 * API documentation for Karasu Lab
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CharactersControllerUpdateRequest {
    'id': string;
    'name'?: string;
    'description'?: string;
    'iconUrl'?: string;
    'headerImgUrl'?: string;
    'element'?: string;
    'country'?: string;
    'weaponType'?: string;
    'rarity'?: number;
    'version'?: string;
    'unimplemented'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "iconUrl",
            "baseName": "icon_url",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "headerImgUrl",
            "baseName": "header_img_url",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "element",
            "baseName": "element",
            "type": "string",
            "format": ""
        },
        {
            "name": "country",
            "baseName": "country",
            "type": "string",
            "format": ""
        },
        {
            "name": "weaponType",
            "baseName": "weapon_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "rarity",
            "baseName": "rarity",
            "type": "number",
            "format": ""
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "string",
            "format": ""
        },
        {
            "name": "unimplemented",
            "baseName": "unimplemented",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CharactersControllerUpdateRequest.attributeTypeMap;
    }

    public constructor() {
    }
}
