/**
 * Karasu Lab API production
 * API documentation for Karasu Lab
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ArtifactSets } from '../models/ArtifactSets';
import { Country } from '../models/Country';
import { Gallery } from '../models/Gallery';
import { VersionsEntity } from '../models/VersionsEntity';
import { Weapon } from '../models/Weapon';
import { HttpFile } from '../http/http';

export class Character {
    'id': string;
    'name': string;
    'description': string;
    'iconUrl': string;
    'element'?: string;
    'rarity'?: number;
    'headerImgUrl': string;
    'weaponType'?: string;
    'property'?: string;
    'uninplemented': boolean;
    'createdAt': Date;
    'updatedAt': Date;
    'country'?: Country | null;
    'weapon'?: Weapon | null;
    'artifactSet': Array<ArtifactSets>;
    'galleries'?: Array<Gallery> | null;
    'version': VersionsEntity;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "iconUrl",
            "baseName": "icon_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "element",
            "baseName": "element",
            "type": "string",
            "format": ""
        },
        {
            "name": "rarity",
            "baseName": "rarity",
            "type": "number",
            "format": ""
        },
        {
            "name": "headerImgUrl",
            "baseName": "header_img_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "weaponType",
            "baseName": "weapon_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "property",
            "baseName": "property",
            "type": "string",
            "format": ""
        },
        {
            "name": "uninplemented",
            "baseName": "uninplemented",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "country",
            "baseName": "country",
            "type": "Country",
            "format": ""
        },
        {
            "name": "weapon",
            "baseName": "weapon",
            "type": "Weapon",
            "format": ""
        },
        {
            "name": "artifactSet",
            "baseName": "artifact_set",
            "type": "Array<ArtifactSets>",
            "format": ""
        },
        {
            "name": "galleries",
            "baseName": "galleries",
            "type": "Array<Gallery>",
            "format": ""
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "VersionsEntity",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Character.attributeTypeMap;
    }

    public constructor() {
    }
}
