/**
 * Karasu Lab API production
 * API documentation for Karasu Lab
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CharactersControllerImportRequestModulesInnerComponentsInner } from '../models/CharactersControllerImportRequestModulesInnerComponentsInner';
import { HttpFile } from '../http/http';

export class CharactersControllerImportRequestModulesInner {
    'name': string;
    'isPosed'?: boolean;
    'components'?: Array<CharactersControllerImportRequestModulesInnerComponentsInner>;
    'id': string;
    'isCustomizeName'?: boolean;
    'isAbstract'?: boolean;
    'isShowSwitch'?: boolean;
    '_switch'?: boolean;
    'desc': string;
    'repeated'?: boolean;
    'isSubmodule'?: boolean;
    'originModuleId': string;
    'withoutBorder'?: boolean;
    'canDelete'?: boolean;
    'isHidden'?: boolean;
    'richTextEditing'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "isPosed",
            "baseName": "is_posed",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "components",
            "baseName": "components",
            "type": "Array<CharactersControllerImportRequestModulesInnerComponentsInner>",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "isCustomizeName",
            "baseName": "is_customize_name",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isAbstract",
            "baseName": "is_abstract",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isShowSwitch",
            "baseName": "is_show_switch",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "_switch",
            "baseName": "switch",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "desc",
            "baseName": "desc",
            "type": "string",
            "format": ""
        },
        {
            "name": "repeated",
            "baseName": "repeated",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isSubmodule",
            "baseName": "is_submodule",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "originModuleId",
            "baseName": "origin_module_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "withoutBorder",
            "baseName": "without_border",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "canDelete",
            "baseName": "can_delete",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isHidden",
            "baseName": "is_hidden",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "richTextEditing",
            "baseName": "rich_text_editing",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CharactersControllerImportRequestModulesInner.attributeTypeMap;
    }

    public constructor() {
    }
}
