/**
 * Karasu Lab API production
 * API documentation for Karasu Lab
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CharactersControllerImportRequestExtPostExt {
    'postId': string;
    'postUserName': string;
    'postTime': string;
    'postAvaterUrl'?: string;
    'url': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "postId",
            "baseName": "post_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "postUserName",
            "baseName": "post_user_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "postTime",
            "baseName": "post_time",
            "type": "string",
            "format": ""
        },
        {
            "name": "postAvaterUrl",
            "baseName": "post_avater_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CharactersControllerImportRequestExtPostExt.attributeTypeMap;
    }

    public constructor() {
    }
}
