/**
 * Karasu Lab API production
 * API documentation for Karasu Lab
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CharactersControllerImportRequestExt } from '../models/CharactersControllerImportRequestExt';
import { CharactersControllerImportRequestFilterValues } from '../models/CharactersControllerImportRequestFilterValues';
import { CharactersControllerImportRequestModulesInner } from '../models/CharactersControllerImportRequestModulesInner';
import { HttpFile } from '../http/http';

export class CharactersControllerImportRequest {
    'id': string;
    'name': string;
    'desc': string;
    'iconUrl': string;
    'headerImgUrl': string;
    'modules'?: Array<CharactersControllerImportRequestModulesInner>;
    'filterValues': CharactersControllerImportRequestFilterValues;
    'menuId': string;
    'menuName': string;
    'version': string;
    'langs'?: Array<string>;
    'templateLayout': any | null;
    'editLockStatus': string;
    'correctLockStatus': string;
    'templateId': string;
    'ext': CharactersControllerImportRequestExt;
    'aliasName': string;
    'lang': string;
    'beta'?: boolean;
    'pageType': string;
    'menuStyle': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "desc",
            "baseName": "desc",
            "type": "string",
            "format": ""
        },
        {
            "name": "iconUrl",
            "baseName": "icon_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "headerImgUrl",
            "baseName": "header_img_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "modules",
            "baseName": "modules",
            "type": "Array<CharactersControllerImportRequestModulesInner>",
            "format": ""
        },
        {
            "name": "filterValues",
            "baseName": "filter_values",
            "type": "CharactersControllerImportRequestFilterValues",
            "format": ""
        },
        {
            "name": "menuId",
            "baseName": "menu_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "menuName",
            "baseName": "menu_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "string",
            "format": ""
        },
        {
            "name": "langs",
            "baseName": "langs",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "templateLayout",
            "baseName": "template_layout",
            "type": "any",
            "format": ""
        },
        {
            "name": "editLockStatus",
            "baseName": "edit_lock_status",
            "type": "string",
            "format": ""
        },
        {
            "name": "correctLockStatus",
            "baseName": "correct_lock_status",
            "type": "string",
            "format": ""
        },
        {
            "name": "templateId",
            "baseName": "template_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "ext",
            "baseName": "ext",
            "type": "CharactersControllerImportRequestExt",
            "format": ""
        },
        {
            "name": "aliasName",
            "baseName": "alias_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "lang",
            "baseName": "lang",
            "type": "string",
            "format": ""
        },
        {
            "name": "beta",
            "baseName": "beta",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "pageType",
            "baseName": "page_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "menuStyle",
            "baseName": "menu_style",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CharactersControllerImportRequest.attributeTypeMap;
    }

    public constructor() {
    }
}
