/**
 * Karasu Lab API production
 * API documentation for Karasu Lab
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CharactersControllerImportRequestModulesInnerComponentsInner {
    'componentId': string;
    'layout': string;
    'data'?: string;
    'style': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "componentId",
            "baseName": "component_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "layout",
            "baseName": "layout",
            "type": "string",
            "format": ""
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "string",
            "format": ""
        },
        {
            "name": "style",
            "baseName": "style",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CharactersControllerImportRequestModulesInnerComponentsInner.attributeTypeMap;
    }

    public constructor() {
    }
}
