/**
 * Karasu Lab Auth API Document Production
 * API documentation for Karasu Lab
 *
 * OpenAPI spec version: 3.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class GalleriesControllerGetRequest {
    'id'?: string;
    'alt'?: string;
    'url'?: string;
    'take'?: string;
    'skip'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "alt",
            "baseName": "alt",
            "type": "string",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": ""
        },
        {
            "name": "take",
            "baseName": "take",
            "type": "string",
            "format": ""
        },
        {
            "name": "skip",
            "baseName": "skip",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GalleriesControllerGetRequest.attributeTypeMap;
    }

    public constructor() {
    }
}
