/**
 * Karasu Lab Auth API Document Production
 * API documentation for Karasu Lab
 *
 * OpenAPI spec version: 3.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ArtifactSets } from '../models/ArtifactSets';
import { Country } from '../models/Country';
import { Gallery } from '../models/Gallery';
import { VersionsEntity } from '../models/VersionsEntity';
import { Weapon } from '../models/Weapon';
import { HttpFile } from '../http/http';

export class GICharacter {
    'id': string;
    'name': string;
    'description'?: string | null;
    'icon_url': string;
    'element'?: string | null;
    'rarity'?: number | null;
    'header_img_url': string | null;
    'weapon_type'?: string | null;
    'property'?: string | null;
    'uninplemented': boolean;
    'createdAt': Date;
    'updatedAt': Date;
    'region'?: Country | null;
    'weapon'?: Weapon | null;
    'version': VersionsEntity;
    'artifact_set': Array<ArtifactSets>;
    'galleries': Array<Gallery>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "icon_url",
            "baseName": "icon_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "element",
            "baseName": "element",
            "type": "string",
            "format": ""
        },
        {
            "name": "rarity",
            "baseName": "rarity",
            "type": "number",
            "format": ""
        },
        {
            "name": "header_img_url",
            "baseName": "header_img_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "weapon_type",
            "baseName": "weapon_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "property",
            "baseName": "property",
            "type": "string",
            "format": ""
        },
        {
            "name": "uninplemented",
            "baseName": "uninplemented",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "region",
            "baseName": "region",
            "type": "Country",
            "format": ""
        },
        {
            "name": "weapon",
            "baseName": "weapon",
            "type": "Weapon",
            "format": ""
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "VersionsEntity",
            "format": ""
        },
        {
            "name": "artifact_set",
            "baseName": "artifact_set",
            "type": "Array<ArtifactSets>",
            "format": ""
        },
        {
            "name": "galleries",
            "baseName": "galleries",
            "type": "Array<Gallery>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GICharacter.attributeTypeMap;
    }

    public constructor() {
    }
}
