/**
 * Karasu Lab API production
 * API documentation for Karasu Lab
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ArtifactSets } from '../models/ArtifactSets';
import { Artifacts } from '../models/Artifacts';
import { Character } from '../models/Character';
import { Country } from '../models/Country';
import { Weapon } from '../models/Weapon';
import { HttpFile } from '../http/http';

export class VersionsEntity {
    'id': string;
    'name'?: string;
    'versionString': string;
    'released': boolean;
    'createdAt': Date;
    'updatedAt': Date;
    'entities': Array<Weapon>;
    'artifactSets': Array<ArtifactSets>;
    'countries': Array<Country>;
    'characters': Array<Character>;
    'artifacts': Array<Artifacts>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "versionString",
            "baseName": "version_string",
            "type": "string",
            "format": ""
        },
        {
            "name": "released",
            "baseName": "released",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "entities",
            "baseName": "entities",
            "type": "Array<Weapon>",
            "format": ""
        },
        {
            "name": "artifactSets",
            "baseName": "artifact_sets",
            "type": "Array<ArtifactSets>",
            "format": ""
        },
        {
            "name": "countries",
            "baseName": "countries",
            "type": "Array<Country>",
            "format": ""
        },
        {
            "name": "characters",
            "baseName": "characters",
            "type": "Array<Character>",
            "format": ""
        },
        {
            "name": "artifacts",
            "baseName": "artifacts",
            "type": "Array<Artifacts>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return VersionsEntity.attributeTypeMap;
    }

    public constructor() {
    }
}
