/**
 * Karasu Lab Auth API Document Production
 * API documentation for Karasu Lab
 *
 * OpenAPI spec version: 3.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ArtifactSets } from '../models/ArtifactSets';
import { Artifacts } from '../models/Artifacts';
import { Country } from '../models/Country';
import { GICharacter } from '../models/GICharacter';
import { Weapon } from '../models/Weapon';
import { HttpFile } from '../http/http';

export class VersionsEntity {
    'id': string;
    'name'?: string | null;
    'version_string': string;
    'released': boolean;
    'createdAt': Date;
    'updatedAt': Date;
    'characters': Array<GICharacter>;
    'weapons'?: Array<Weapon> | null;
    'artifact_sets'?: Array<ArtifactSets> | null;
    'countries'?: Array<Country> | null;
    'artifacts'?: Array<Artifacts> | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "version_string",
            "baseName": "version_string",
            "type": "string",
            "format": ""
        },
        {
            "name": "released",
            "baseName": "released",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "characters",
            "baseName": "characters",
            "type": "Array<GICharacter>",
            "format": ""
        },
        {
            "name": "weapons",
            "baseName": "weapons",
            "type": "Array<Weapon>",
            "format": ""
        },
        {
            "name": "artifact_sets",
            "baseName": "artifact_sets",
            "type": "Array<ArtifactSets>",
            "format": ""
        },
        {
            "name": "countries",
            "baseName": "countries",
            "type": "Array<Country>",
            "format": ""
        },
        {
            "name": "artifacts",
            "baseName": "artifacts",
            "type": "Array<Artifacts>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return VersionsEntity.attributeTypeMap;
    }

    public constructor() {
    }
}
