/**
 * Karasu Lab Auth API Document Production
 * API documentation for Karasu Lab
 *
 * OpenAPI spec version: 3.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GICharacter } from '../models/GICharacter';
import { VersionsEntity } from '../models/VersionsEntity';
import { HttpFile } from '../http/http';

export class Weapon {
    'id': string;
    'name': string;
    'createdAt': Date;
    'updatedAt': Date;
    'description'?: string | null;
    'icon_url': string;
    'rarity': number;
    'effect': string;
    'type': string;
    'characters': Array<GICharacter>;
    'version': VersionsEntity;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "icon_url",
            "baseName": "icon_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "rarity",
            "baseName": "rarity",
            "type": "number",
            "format": ""
        },
        {
            "name": "effect",
            "baseName": "effect",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "characters",
            "baseName": "characters",
            "type": "Array<GICharacter>",
            "format": ""
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "VersionsEntity",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Weapon.attributeTypeMap;
    }

    public constructor() {
    }
}
